### ISSUE TITLE
No new buffer on `pest-test-grammar`

### ISSUE THREAD

**Issue by lerouxrgd** [ksqsf/pest-mode#1]
It looks like it got delete on [last commit](https://github.com/ksqsf/pest-mode/commit/c522650aeb0d2b7700a733659f2b5e03c5ef5fbc#diff-62c29dabd74b80e99e16e6b3146b4bc9L180), is this normal ?

**Comment by ksqsf** [comment]
Thanks for catching this! A stupid mistake...
